services:
  - type: web
    name: hirehi-kotlin
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    envVars:
      - key: PORT
        value: 10000
      - key: JAVA_OPTS
        value: "-Xmx512m -Xms256m"
    healthCheckPath: /api/status
    autoDeploy: true
